version: "3.9"

services:
  userservice:
    build:
      context: userservice
    ports:
      - "3000:3000"
    volumes:
      - ./userservice/src:/app/src
      - ./userservice/tests:/app/tests
    command: ["npm", "run", "dev"]

  webapp:
    build:
      context: webapp
    ports:
      - "8000:8000"
    volumes:
      - ./webapp:/app
    environment:
      - ENV=development
      - SECRET_KEY=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=devuser
      - DB_PASS=mypassword
      - USER_SERVICE_ENDPOINT=http://userservice:3000
    depends_on:
      - db
      - userservice
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py runserver 0.0.0.0:8000"

  db:
    image: postgres:13-alpine
    volumes:
      - dev-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=mypassword
    ports:
      - "5432:5432"

volumes:
  dev-data:
