# Generated by Django 4.2.6 on 2023-10-25 15:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="permission_codes",
            field=models.CharField(default="", max_length=511),
            preserve_default=False,
        ),
    ]
