# Generated by Django 4.2.6 on 2023-10-25 14:47

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(max_length=2000)),
                ("stock", models.PositiveIntegerField()),
                ("image", models.URLField(max_length=1023)),
            ],
        ),
    ]
